### ISSUE TITLE
Where are XTrkCadReader production releases?

### ISSUE THREAD

**Issue by mstevetodd** [JMRI/XTrkCadReader#6]
At the top of this page (https://github.com/JMRI/XTrkCadReader) there is a link to http://jmri.org/community/connections/XtrkCadReader/ but the download file on that page is much older than the source on GitHub. The included XTrkCadReader.jar file shows a date of 4/8/2013. The github source was last changed on 12/21/2016.
The reason I ask is that an XTrkCadReader user encountered an error that has been fixed in the GitHub source, and I'd like to point him to the latest release containing that fix. See thread here: https://groups.yahoo.com/neo/groups/jmriusers/conversations/topics/136444

**Comment by mattharris** [comment]
I've been meaning to get onto that, but have not had the time to finish up the refactoring work that I started, along with some bug fixes.

**Comment by bobjacobsen** [comment]
When we do get a release for XTrkCadReader, I recommend making it available through the GitHub release system.  Seems to be working well with JMRI now.

**Comment by bobjacobsen** [comment]
I'm going to put a new .jar file from PR #7 up to SourceForge, but it would be good to get the infrastructure set up.

**Comment by pabender** [comment]
Once we take care of #4, don't the release instructions just become part of the Jmri instructions?

**Comment by bobjacobsen** [comment]
> Once we take care of #4, don't the release instructions just become part of the Jmri instructions?

Depends on the approach taken for #4, I think.  

And some of those approaches might take a bit of time before they're done....

**Comment by mattharris** [comment]
Sorry - not been able to devote any time to JMRI stuff for the past few months.

#5 should put in-place a build mechanism to generate the distribution file via ant, rather than the previous manual work. This should help get us a few more steps along the way towards #4.

**Comment by silverailscolo** [comment]
As of today, with assistance from @bobjacobsen, the latest release of XtrkCadReader [version 2.2.2](https://github.com/JMRI/XTrkCadReader/pull/9) can be downloaded directly from [GitHub/JMRI/XTrkCadReader/Releases/](https://github.com/JMRI/XTrkCadReader/releases). I reckon this clears up this issue, and makes all the remaining downloadable items on sourceforge.org redundant. Suggestions for new features for 2.2.3 welcome, of course.
@mstevetodd can you confirm and close this issue?

**Comment by mstevetodd** [comment]
Looks good. Thank you!
